title: Planning Hell
description: Where bad ideas meet a drawing board

url: https://planninghell.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about

disqus:
    shortname: my-disqus-shortname
